- Plugin:
    name: deis
    search: deis-plugin

- World:
    lines:
      - [ -5, -5,  5, -5 ]
      - [  5, -5,  5,  5 ]
      - [  5,  5, -5,  5 ]
      - [ -5,  5, -5, -5 ]

- Object:
    name: pie_base
    parent: world
    mount: [ 0.0, -2.5, 0.2 ]
    lines:
      - [ -0.2, -0.4,  0.4, -0.2 ]
      - [ -0.2,  0.4,  0.4,  0.2 ]
      - [  0.4, -0.2,  0.4,  0.2 ]
      - [ -0.2,  0.4, -0.2, -0.4 ]
- DifferentialDrive:
    name: pie_drive
    parent: pie_base
    wheel_radius: 0.2
    wheel_base: 0.3
- RayDistanceSensor:
    name: left_sensor
    parent: pie_base
    mount: [ 0.1, 0.1, 0.35 ]
    max_distance: 2.5
- RayDistanceSensor:
    name: right_sensor
    parent: pie_base
    mount: [ 0.1, -0.1, -0.35 ]
    max_distance: 2.5

- DEISProcess:
    left_sensor: left_sensor
    right_sensor: right_sensor
    drive: pie_drive

- Simulator:
    timestep: 0.1
    state: pause

- ObjectCamera:
    name: world_camera
    object: world
- ObjectDrawing:
    name: world_drawing
    object: world
- View:
    name: world_view
    camera: world_camera
    drawings:
      - world_drawing
